before_install:
 - source ./texlive/texlive_install.sh
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
script:
- pdflatex -interaction=nonstopmode ./CM_ComplPro.tex
- pdflatex -interaction=nonstopmode ./CM_ComplPro.tex
deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_TOKEN
  file:
   - ./CM_ComplPro.pdf
  skip_cleanup: true
  on:
    tags: false
